 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 156-569-404
Traceback (most recent call last):
  File "flaskStudy.py", line 12, in <module>
    app.run()
  File "/usr/python-3.6.4/lib/python3.6/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/usr/python-3.6.4/lib/python3.6/site-packages/werkzeug/serving.py", line 795, in run_simple
    s.bind(get_sockaddr(hostname, port, address_family))
OSError: [Errno 98] Address already in use
 * Detected change in '/root/myPython/myTestPython/flaskStudy.py', reloading
 * Running on http://0.0.0.0:9090/ (Press CTRL+C to quit)
192.168.0.169 - - [16/Mar/2018 11:24:53] "[37mGET / HTTP/1.1[0m" 200 -
192.168.0.169 - - [16/Mar/2018 11:24:53] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
